project:
  type: website
  output-dir: docs

website:
  title: "E. Pitzer | Data Analyst"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Case Studies  # <--- Changed from "Projects" or "Engineering"
      - href: dashboards.qmd
        text: Dashboards    # <--- Explicit and clear
    right:
      - icon: github
        href: https://github.com/pitzer-e
      - icon: linkedin
        href: https://www.linkedin.com/in/pitzer-e/
      - icon: journal-code # Using a generic icon for Kaggle if the specific brand icon isn't loaded yet
        href: https://www.kaggle.com/epitzer
        text: Kaggle 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true